"""sync jobs schema

Revision ID: 462b8f3442b2
Revises: 
Create Date: 2026-01-18 23:13:28.320323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462b8f3442b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('recovered_raw_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('recovered_size_bytes', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('first_mismatch_offset', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('original_size_bytes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'original_size_bytes')
    op.drop_column('jobs', 'first_mismatch_offset')
    op.drop_column('jobs', 'recovered_size_bytes')
    op.drop_column('jobs', 'recovered_raw_path')
    # ### end Alembic commands ###
