"""add ot2 fields to jobs

Revision ID: a0c0625ed1ba
Revises: 7f98813f53db
Create Date: 2026-02-05 13:05:56.796926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c0625ed1ba'
down_revision: Union[str, Sequence[str], None] = '7f98813f53db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('ot2_host', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('ot2_remote_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('ot2_run_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'ot2_run_status')
    op.drop_column('jobs', 'ot2_remote_path')
    op.drop_column('jobs', 'ot2_host')
    # ### end Alembic commands ###
