name: Pi Deploy

on:
  push:
    branches: [ Main ] # Or whatever your team's main branch is

jobs:
  deploy:
    runs-on: self-hosted  # <--- This tells GitHub to talk to your Pi
    steps:
      - name: Fix Workspace Permissions
        # Uses a temporary root docker container to change ownership back to the runner's UID/GID
        run: docker run --rm -v ${{ github.workspace }}:/workspace alpine chown -R $(id -u):$(id -g) /workspace

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # If you have submodules, this will fetch them too

      - name: Copy Env Files
        run: |
          # Copy root env (for the tunnel token)
          cp /home/biocompute/biocompute-poc/BioCompute-POC/.env .
          
          # Copy backend env
          cp /home/biocompute/biocompute-poc/BioCompute-POC/backend/.env ./backend/.env
          
          # Copy frontend env
          cp /home/biocompute/biocompute-poc/BioCompute-POC/frontend/poc-frontend/.env.local ./frontend/poc-frontend/.env.local

      - name: Build and Run
        run: |
          docker compose -f docker-compose.yml --profile prod up -d --build
          docker compose -f docker-compose.yml restart poc_nginx